### PR TITLE
Better Windows Support

### PR DESCRIPTION
**Pull request by cboushehri**
I used the Microsoft Keyboard Layout Creator to make a real layout, and a couple of registry hacks to rebind the modifier keys. It works at the login screen and in system programs. The only remaining problem is the lack of cursor keys. 

I know it installs properly on Windows 7. I have not tried 10 or other versions.

### CODE REVIEW

**Comment by jackrosenthal** [comment]
Do you think you could walk me thru and/or write instructions on making the binaries? Once we get these removed and squished from the repo, should be good to go.

Would like to have the repository binary-free ;) We can put these in a GitHub releases.

**Comment by cboushehri** [comment]
Load 3l.klc in Microsoft Keyboard Layout Creator (https://www.microsoft.com/en-us/download/details.aspx?id=22339).

Under Project, click Build DLL and Setup Package. It will generate all the files, and create the installer.

**Comment by cboushehri** [comment]
3l.skl is a list of keys to be overwritten in the registry. Other than those two files, and the install guide, everything else can go.

**Comment by jackrosenthal** [comment]
Hey @cboushehri ,

I think I'm going to close this without merging, simply because the limitations imposed by the Windows keyboard driver makes this way more roundabout of a solution than the AHK script. This way, we can just keep recommending the AHK script to newcomers (due to it's ease of setup).

I'll also close #4 , simply as it's just not quite feasible.

Jack

**Pull request closed without merging**
